# Generated by Django 2.0.5 on 2018-05-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='liked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
    ]
